### ISSUE TITLE
Receiving a 404 error on import/restore from Door43

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#620]
When I try to import/restore my project from Door43 I receive the following error.

I am logged into tS-Desktop with my Door43 account.
![404 error](https://cloud.githubusercontent.com/assets/9850185/15867288/90881062-2cb0-11e6-8130-92f885321391.png)

**Comment by tjklemz** [comment]
@cdwhitfield73 I believe this is due to a bad API url in the settings (i.e. it's still gitolite or something instead of door43). Simply clear the tsDesktop cache on the system, and this error should fix itself.

**Comment by cdwhitfield73** [comment]
It was decided for now that the fix for this is to hard code the server url in the import function rather than use the user setting.  The user setting is displayed in the settings page but is not enabled for the user to change it.

**Comment by cckozie** [comment]
The app appears to be accessing Gogs when I do an import so it looks like that part of it is hard coded. However, when I installed 9.0 onto a machine that had 5.0 installed, the Settings window in 9.0 still show the 5.0 data server settings.
![image](https://cloud.githubusercontent.com/assets/8171759/16208076/145979b8-36f6-11e6-9c63-123bb4e68d1d.png)

**Comment by cdwhitfield73** [comment]
I have fixed this so that it will always set and display the current values that have been hard coded, even if updating from a very old version.
