### ISSUE TITLE
helps in Psalms do not have matching slugs to book chunks

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#970]
Chris Whitfield [2:19 PM]  
I found an issue with Psalms resource containers.  Not sure if the problem is in the api or your client.  The "book" containers are fine, formatting chapter folder names and file names correctly, with two characters minimum (adding a leading zero to single digits).  But the tN and tQ containers are naming files and folders with 3 characters minimum (two leading zeroes on single, etc.).  This causes the app to not be able to match the resources with the source.

[2:21]  
what's weird is that tN is doing both file and folder names, but tQ is just doing it to folder names (file names are correct)

**Comment by cdwhitfield73** [comment]
We also just found other problems in Psalms resource containers.  Something bad is happening around chapter 119.  Several chunks are being combined together incorrectly in several versions.  Look at the Russian source.  Chapter 118, chunk 29 has about 100 verses in it and chapter 119 is almost empty.

**Comment by neutrinog** [comment]
This is definitely a bug in the api. See https://api.unfoldingword.org/ts/txt/2/psa/ru/rsb/source.json?date_modified=20161104 search for "118" and notice there is a HUGE chunk that contains most of chapter 119.

**Comment by neutrinog** [comment]
@phillip-hopper can you help us get this issue pointed to the correct person?

**Comment by neutrinog** [comment]
the modules for android and desktop have both been updated to normalize all the book and help slugs.

**Comment by phillip-hopper** [comment]
@neutrinog Many of the orthodox Bibles have an alternate versification system for the book of Psalms. What they do is combine chapters 9 and 10 into one chapter, 9. This throws the chapter numbers off until you get to 147. They split our chapter 147 into 2 chapters, their 146 and 147, which results in still having 150 chapters in Psalms. The Russian Bible is using the versification system found here: https://github.com/unfoldingWord-dev/uw-api/blob/develop/static/versification/rsc/rsc.vrs.

**Comment by phillip-hopper** [comment]
@neutrinog I will take a look at the English ULB to try to find the problem. The UDB looks correct, so I'm not sure what happened there.

**Comment by neutrinog** [comment]
Ok we still don't have a good method of displaying different versification systems in the app. There is a proposal to do so in https://github.com/unfoldingWord-dev/ts-requirements/issues/139

**Comment by phillip-hopper** [comment]
@jag3773 & @neutrinog Another thing to keep in mind is that, even in English, most psalms have a verse `\v 0` which is the inspired heading, like "For the choir director. A Psalm of David."

**Comment by cdwhitfield73** [comment]
@phillip-hopper says that the ULB chunk issue is fixed.  Will pull in the new data and confirm.  Removing the help wanted tag.

**Comment by cckozie** [comment]
There are still some resources not being displayed in Psalms. For example, after installing build 95, chunk 1 of Psalm 15 was only showing Notes even though there are data for this chunk in both tQ and the UDB. After updating the list of available source texts and downloading the English ULB and UDB, both Notes and UDB show for that chunk, but Questions still do not even though there is question in the resource file for that chunk.

**Comment by cdwhitfield73** [comment]
The issue of missing words and questions in Psalms was addressed in issue #993.

**Comment by cckozie** [comment]
In build 100, the tQ tab is not displayed for most chunks >= Psalm 100 even though there are entries in the resource container. No change after download the English ULB and UDB for Psalms.

**Comment by cckozie** [comment]
I don't know if this is the same or a different issue, but there are many chunks in Ezra missing tabs for questions, words, and/or UDB.

**Comment by cdwhitfield73** [comment]
There was an issue with how the questions were being sorted that caused the problem with chapters above 100.  This is fixed.  I can't duplicate the Ezra issue.  Mine looks fine.  The next build will also have a brand new data package.  Let me know if you still find problems.

**Comment by cckozie** [comment]
In build 101:
The UDB is only showing up in chapters 2 and 4 in Ezra even though there looks to be UDB content for the whole book in the resource_containers folder.
The tQ and tW entries are now being displayed appropriately as they reflect what is in the source files.

**Comment by cdwhitfield73** [comment]
I just pulled in a new data package and UDB is showing for me for all chunks of Ezra.  Retest on next build.

**Comment by cckozie** [comment]
I have not found any issues of missing resource tabs/data with build 102
